### ISSUE TITLE
Very large text with pronunciation helper fails

### ISSUE THREAD

**Issue by travisapple** [hexgrad/kokoro#42]
For short text this works fine but for very long text (my test was 40k chars, so a chapter of a book) the pronunciation hint in the form of

`[Kokoro](/kˈOkəɹO/)
`
is ignored. It will pronounce BOTH the first and second parts. Again, this only occurs on extremely long text inputs and the workaround is manually splitting the text and running it separately for each part.

**Comment by hexgrad** [comment]
Is your text 40k chars with no newlines? The default behavior is to split on newlines:
https://github.com/hexgrad/kokoro/blob/2f4d94bba25dc73e05ec4a9ffdee72f1d46fdd5c/kokoro/pipeline.py#L233-L240

Either way will take a look at this, but another fix in the meantime is to reach into the `G2P` class and directly override the gold lexicon like this:
```py
pipelines = {lang_code: KPipeline(lang_code=lang_code, model=False) for lang_code in 'ab'}
pipelines['a'].g2p.lexicon.golds['kokoro'] = 'kˈOkəɹO'
pipelines['b'].g2p.lexicon.golds['kokoro'] = 'kˈQkəɹQ'
```
https://huggingface.co/spaces/hexgrad/Kokoro-TTS/blob/136465fbffad342a1de9e44cc326ea75090a1828/app.py#L13-L15

Recommend you only do that for proper nouns, and still use the Markdown syntax for common words or homographs.

**Comment by travisapple** [comment]
It's 40k WITH newlines. Never more than ~300 chars per paragraph but sometimes it will split by sentence. Splitting by sentence doesn't seem to affect this issue.

Some context, I want a book reader. The book has some wild character names and so I do a search and replace on these names with pronunciations.

I'll take a hard look at the G2P options in the morning and THANK YOU for your time

**Comment by travisapple** [comment]
It's copyrighted for sure. I'm attaching a zip file with what you need. Run fulltext.txt and then I'm attaching a sample output that shows the effect I'm getting.

https://litter.catbox.moe/pz1ew5.zip

**Comment by hexgrad** [comment]
@travisapple Updating to `kokoro >= 0.7.3` should resolve that bug

**Comment by travisapple** [comment]
I can see on my end that this has been fixed. THANK YOU for your time and effort

**Comment by travisapple** [comment]
I found another related issue here. 

```

from kokoro import KModel,KPipeline
import pydub # for mp3 creation
import numpy as np # for mp3 creation

fulltext = '''Last night, Elayne had said, [Egwene](/ˈiɡwˈAn/) reported fighting in [Cairhien](/kˈɛː hˈiːn/), skirmishes with brigands, with [Cairhien](/kˈɛː hˈiːn/)in who saw any [Aiel](/ˈAˈil/) as an enemy, with Andoran soldiers trying to claim the Sun Throne for [Morgase](/mˈɔːɡˈAz/). Lan had been involved in them; whenever [Moiraine](/mʊɹˈAn/) let him out of her sight, he apparently managed to take himself to the fighting, as if he could sense where it would be. [Nynaeve](/nˈInˈiːv/) had never thought that she would want the [Aes Sedai](/ˈI sɪdˈI/) to keep Lan on a short leash at her side.'''

model = KModel().to('cuda').eval()
pipeline = KPipeline(lang_code='b', model=model)
generator = pipeline(
	fulltext,
	voice = 'bf_emma',
	speed = 1.1146358814550124
)

for i, result in enumerate(generator):
	audio = result.audio.cpu().numpy()
	audio = np.int16(audio * 2 ** 15)
	sound = pydub.AudioSegment(audio.squeeze().tobytes(), frame_rate=24000, sample_width=2, channels=1)
	sound.export('test.mp3', format='mp3', bitrate='170k')

```
This will create a file that shows the issue. The first 3 word helpers are fine and then the rest are repeated.

**Comment by hexgrad** [comment]
You have what is probably a typo here `[Cairhien](/kˈɛː hˈiːn/)in` @travisapple 

Still not functionally correct, but I suspect fixing that will resolve your issue. Also, consider overriding the dictionary instead of using the `[]()` syntax.

**Comment by travisapple** [comment]
I'll just switch to the dictionary method but I believe I'll need both eventually. Is the problem with the above text that there needs to be a space before "in"?
If you run this code you'll find that it will fail at instances without this issue.

**Comment by travisapple** [comment]
It does fix it and now that I know you need spaces around everything it should be fine. However, it might be preferable if the spaces were not required.
